sudo: required
os:
  - linux
language: node_js
node_js:
  - "8"
cache:
  - npm
  - directories:
      - "$HOME/.npm"
      - node_modules
before_script:
  - npm install
script:
  - npm test
after_success:
  - echo 'all test passed'
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/
