name: UT
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
env:
  NODE_VERSION: "8.x"

jobs:
  build:
    runs-on: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install
        run: npm install

      - name: run UT
        run: npm run test --if-present
